function cAPI.createCamera()
	local ped = PlayerPedId()
	FreezeEntityPosition(GetPlayerPed(-1), true)
	SetEntityVisible(PlayerPedId(),false)
    SetTimecycleModifier('Base_modifier')
    cam = CreateCamWithParams("DEFAULT_SCRIPTED_CAMERA", 500.02, 500.02, 250.93, 360.00,0.00,0.00, 100.00, false, 0)    
	PointCamAtCoord(cam, 500.02-25, 500.02-70, 250.93-20)
    SetCamActive(cam, true)
    RenderScriptCams(true, false, 1, true, true)
	DisplayHud(false)
    DisplayRadar(false)    
end

function cAPI.destroyCamera()
	DestroyAllCams(true)
	Citizen.Wait(500)
	FreezeEntityPosition(GetPlayerPed(-1), false)
	SetEntityVisible(PlayerPedId(),true)
	DisplayHud(true)
	DisplayRadar(true)	
end

function cAPI.CameraWithSpawnEffect(coords)
    cAPI.destroyCamera()
	cam = CreateCamWithParams("DEFAULT_SCRIPTED_CAMERA", coords.x+200,coords.y+200,coords.z+200, 300.00,0.00,0.00, 100.00, false, 0) -- CAMERA COORDS
	PointCamAtCoord(cam, coords.x,coords.y,coords.z+200)
	SetCamActive(cam, true)
	cAPI.EndFade(500)
	RenderScriptCams(true, false, 1, true, true)
	Citizen.Wait(500)
	cam3 = CreateCamWithParams("DEFAULT_SCRIPTED_CAMERA", coords.x,coords.y,coords.z+200, 300.00,0.00,0.00, 100.00, false, 0)
	PointCamAtCoord(cam3, coords.x,coords.y,coords.z+200)
	SetCamActiveWithInterp(cam3, cam, 3900, true, true)
	Citizen.Wait(3900)
	cam2 = CreateCamWithParams("DEFAULT_SCRIPTED_CAMERA", coords.x,coords.y,coords.z+200, 300.00,0.00,0.00, 100.00, false, 0)
	PointCamAtCoord(cam2, coords.x,coords.y,coords.z+2)
	SetCamActiveWithInterp(cam2, cam3, 3700, true, true)
	RenderScriptCams(false, true, 500, true, true)
	SetEntityCoords(PlayerPedId(), coords.x, coords.y, coords.z+0.5)
	Citizen.Wait(1500)
	DestroyAllCams(true)
	Citizen.Wait(800)
	DisplayHud(true)
	DisplayRadar(true)	
	TriggerEvent('ToogleBackCharacter')
end 
