// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '<b>{0}</b>: {1}',
    'defaultAlt': '{0}',
    'print': '<pre>{0}</pre>',
    'example:important': '<h1>^2{0}</h1>'
  },
  fadeTimeout: 7000,
  suggestionLimit: 5,
  style: {
    background: 'rgba(0, 0, 0, 0.6)',
    borderRadius: '8px',

    borderLeft: "0.5px solid rgba(255, 255, 255, 0.2)",
    borderRight: "0.5px solid rgba(255, 255, 255, 0.2)",

    borderTop: "0.5px solid rgba(255, 255, 255, 0.1)",
    borderBottom: "0.5px solid rgba(255, 255, 255, 0.1)",

    width: '38%',
    height: '22%',
  }
};
