RegisterNetEvent("myevent:soundStatus")
AddEventHandler("myevent:soundStatus", function(type, musicId, data)
    TriggerClientEvent("myevent:soundStatus", -1, type, musicId, data)
    --print("[SERVER] myevent:soundStatus")
end)

RegisterNetEvent("myevent:stopMusic")
AddEventHandler("myevent:stopMusic", function(musicId)
    TriggerClientEvent("myevent:stopMusic", -1, musicId)
    --print("[SERVER] myevent:soundStatus")
end)

RegisterNetEvent("myevent:pauseMusic")
AddEventHandler("myevent:pauseMusic", function(musicId)
    TriggerClientEvent("myevent:pauseMusic", -1, musicId)
    --print("[SERVER] myevent:soundStatus")
end)

RegisterNetEvent("myevent:changeVolum")
AddEventHandler("myevent:changeVolum", function(musicId, volum)
    TriggerClientEvent("myevent:changeVolum", -1, musicId, volum)
    --print("[SERVER] myevent:soundStatus")
end)

RegisterNetEvent("myevent:resumeMusic")
AddEventHandler("myevent:resumeMusic", function(musicId)
    TriggerClientEvent("myevent:resumeMusic", -1, musicId)
    --print("[SERVER] myevent:soundStatus")
end)